name: build-test-push
run-name: 'build-test-push: versioned? ${{ github.event.inputs.versioned }} - latest? ${{ github.event.inputs.latest }}'

on:
  workflow_dispatch:
    inputs:
      versioned:
        description: 'Push with versioned tag?'
        required: true
        type: boolean
        default: true
      latest:
        description: 'Push with "latest" tag?'
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: matflow-damask:testing
        
      - name: Test
        run: docker run -v $PWD/wd:/wd matflow-damask:testing matflow go simple_damask.yaml
        
      - name: Create tag from damask and matflow versions
        id: tag
        run: |
          damask=$(sed 's|-alpha|a|' <<<"$(grep "FROM" Dockerfile | cut -d':' -f 2)")
          matflow=$(echo $(docker run matflow-damask:testing matflow --version) | cut -d' ' -f 3)
          echo "versions=d${damask}_m${matflow}" >> $GITHUB_OUTPUT
  
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push versioned
        if: github.event.inputs.versioned == 'true'
        run: |
          docker image tag matflow-damask:testing ghcr.io/hpcflow/matflow-damask:${{ steps.tag.outputs.versions }}
          docker push ghcr.io/hpcflow/matflow-damask:${{ steps.tag.outputs.versions }}

      - name: Push latest
        if: github.event.inputs.latest == 'true'
        run: |
          docker image tag matflow-damask:testing ghcr.io/hpcflow/matflow-damask:latest
          docker push ghcr.io/hpcflow/matflow-damask:latest
